config/routes.rb
Rails.application.routes.draw do
  resources :sessions

  get 'pages/index'

  resources :users

  resources :questions do 
    resources :answers
  end

  root 'pages#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

  has_many :answers, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:destroy, :edit, :update]

  def create
    @question = Question.find(params[:question_id]) #находит вопрос
    @answer = @question.answers.create(answers_params)

    if @answer.save 
      redirect_to question_path(@question)
    else
      render 'questions/show'
    end
  end

  def destroy
    @answer.destroy
    redirect_to question_path(@question)
  end

  def edit; end

  def update
    @answer.update(answers_params)
    redirect_to question_path(@question)
  end

  private

  def set_answer
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
  end

  def answers_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ErrorHandling

  private
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id].present?
  end

  def user_signed_in?
    current_user.present?
  end

  helper_method :current_user, :user_signed_in?
end

app/controllers/concerns/error_handling.rb
module ErrorHandling
  extend ActiveSupport::Concern
  
  included do 
    rescue_from ActiveRecord::RecordNotFound, with: :notfound

    private
  
    def notfound(exception)
      logger.warn exception
      render file: 'public/404.html', status: :not_found, layout: false
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :find_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.order(created_at: :desc).page(params[:page])
  end

  def show
    @answer = @question.answers.build
    @answers = @question.answers.order(created_at: :desc).page(params[:page]).per(2) #переменная во вьюхе, вывод вопросов
  end

  def new 
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to questions_path
    else
      render :new
    end
  end

  def edit 
  end

  def update
    if @question.update(question_params)
      redirect_to questions_path
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to @question
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by(email: params[:email])
    if @user&.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to new_session_path
    end
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id #сессия хранилище
      redirect_to root_path
    else
      render :new
   end
  end

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<h3>Edit answer</h3>

<%= form_with model: [@question, @answer] do |f| %>
  <p>
    <%= f.label :body %>
    <%= f.text_field :body %>
  </p>

  <%= f.submit %>
<% end %>

app/views/answers/edit.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Askit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="p-3 bg-dark text-white">
      <div class="container">
        <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><%= link_to 'Home', root_path, class: 'nav-link px-2 text-white' %></li>
            <li><%= link_to 'Questions', questions_path, class: 'nav-link px-2 text-white' %></li>
          </ul>
        </nav>
      </div>
    </header>

    <main class="container mt-3">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Welcome to Askit!</h1>

<% if user_signed_in? %>
  <%= current_user.name %>
<% else %>
  <%= link_to 'Sign_up', new_user_path %>
  <%= link_to 'Log in', new_session_path %>
<% end %>

app/views/questions/_form.html.erb
<%= form_with model: @question do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %>
    <%= f.text_field :body %>
  </p>

  <%= f.submit %>
<% end %>

app/views/questions/edit.html.erb
<%= render 'form' %>

app/views/questions/index.html.erb
<h1>Questions</h1>

<p><%= link_to 'New question', new_question_path, class: 'btn btn-primary' %></p>


<%= paginate @questions %>
<% @questions.each do |question| %>
  <h4><%= link_to question.title, question %></h4>
  <%= question.body %>
  <p></p><%= question.created_at.strftime('%Y-%m-%d %H:%M:%S') %></p>

  
  <%= link_to 'Edit', edit_question_path(question), class: 'btn btn-primary' %>
  <%= link_to 'Delete', question_path(question), method: :delete, class: 'btn btn-danger' %>
<% end %>
<%= paginate @questions %>

app/views/questions/show.html.erb
<p><%= @question.title %></p>
<p><%= @question.body %></p>
<p><%= @question.created_at.strftime('%Y-%m-%d %H:%M:%S') %></p>


<%= render 'answers/form' %>

<%= paginate @answers %>

<% @answers.each do |answer| %>
  <p><%= answer.body %></p>
  <p><%= answer.created_at.strftime('%Y-%m-%d %H:%M:%S') %></p>
  <%= link_to 'Edit answer', edit_question_answer_path(@question, answer) %>
  <%= link_to 'Delete answer', question_answer_path(@question, answer), method: :delete %>
<% end %>

<%= paginate @answers %>

<p><%= link_to 'Back', questions_path %></p>

app/views/users/_form.html.erb
<h1>Create user</h1>

<%= form_with model: @user do |f| %>
  <p>  
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>  
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>  
    <%= f.label :password %>
    <%= f.text_field :password %>
  </p>
  <p>  
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation %>
  </p>
  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<%= render 'form' %>